#!/usr/bin/env python3
"""Create a Gitee pull request from the current git repository."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from typing import Optional
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen


def fail(message: str, exit_code: int = 1) -> None:
    print(f"[ERROR] {message}", file=sys.stderr)
    raise SystemExit(exit_code)


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        joined = " ".join(cmd)
        stderr = result.stderr.strip() or result.stdout.strip()
        fail(f"Command failed: {joined}\n{stderr}")
    return result


def git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return run(["git", *args], check=check)


def ensure_git_repo() -> None:
    probe = git("rev-parse", "--is-inside-work-tree", check=False)
    if probe.returncode != 0 or probe.stdout.strip() != "true":
        fail("Current directory is not a git repository.")


def current_branch() -> str:
    branch = git("rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    if branch == "HEAD":
        fail("Detached HEAD is not supported. Checkout a branch first.")
    return branch


def working_tree_dirty() -> bool:
    return bool(git("status", "--porcelain").stdout.strip())


def auto_commit(commit_message: str) -> None:
    git("add", "-A")
    commit_result = git("commit", "-m", commit_message, check=False)
    if commit_result.returncode != 0:
        stderr = commit_result.stderr.strip() or commit_result.stdout.strip()
        fail(f"Auto commit failed.\n{stderr}")


def parse_gitee_repo_from_remote(remote_url: str) -> Optional[str]:
    patterns = [
        r"^git@gitee\.com:(?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?$",
        r"^ssh://git@gitee\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?/?$",
        r"^https?://(?:[^@/]+@)?gitee\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?/?$",
    ]
    for pattern in patterns:
        match = re.match(pattern, remote_url.strip())
        if match:
            return f"{match.group('owner')}/{match.group('repo')}"
    return None


def resolve_repo(remote: str, explicit_repo: Optional[str]) -> str:
    if explicit_repo:
        return explicit_repo
    env_repo = os.environ.get("GITEE_REPO")
    if env_repo:
        return env_repo
    remote_url = git("config", "--get", f"remote.{remote}.url").stdout.strip()
    parsed = parse_gitee_repo_from_remote(remote_url)
    if parsed:
        return parsed
    fail(
        "Cannot infer Gitee repo from remote URL. "
        "Pass --repo owner/repo or set GITEE_REPO."
    )
    return ""


def resolve_base_branch(remote: str, explicit_base: Optional[str]) -> str:
    if explicit_base:
        return explicit_base
    default_head = git("symbolic-ref", f"refs/remotes/{remote}/HEAD", check=False)
    if default_head.returncode == 0:
        value = default_head.stdout.strip()
        if value:
            return value.split("/")[-1]
    for candidate in ("main", "master"):
        probe = git("show-ref", "--verify", "--quiet", f"refs/remotes/{remote}/{candidate}", check=False)
        if probe.returncode == 0:
            return candidate
    fail("Cannot detect base branch. Pass --base explicitly.")
    return ""


def range_ref(remote: str, base: str, head: str) -> str:
    return f"{remote}/{base}..{head}"


def generate_title(explicit_title: Optional[str], remote: str, base: str, head: str) -> str:
    if explicit_title:
        return explicit_title
    commits = git("log", "--pretty=%s", range_ref(remote, base, head), check=False).stdout.strip().splitlines()
    if commits:
        return commits[0]
    latest = git("log", "-1", "--pretty=%s", check=False).stdout.strip()
    if latest:
        return latest
    return f"Update {head}"


def generate_body(explicit_body: Optional[str], remote: str, base: str, head: str) -> str:
    if explicit_body:
        return explicit_body
    commits = git("log", "--pretty=- %s", range_ref(remote, base, head), check=False).stdout.strip().splitlines()
    commits = [line for line in commits if line.strip()]
    if not commits:
        commits = ["- No new commit detected against base branch."]
    lines = [
        "Auto-generated by gitee-pr skill.",
        "",
        "## Commit Summary",
        *commits[:20],
    ]
    return "\n".join(lines)


def push_branch(remote: str, head: str) -> None:
    push = git("push", "-u", remote, head, check=False)
    if push.returncode != 0:
        stderr = push.stderr.strip() or push.stdout.strip()
        fail(f"Failed to push branch '{head}' to remote '{remote}'.\n{stderr}")


def create_pull_request(
    api_host: str,
    repo: str,
    token: str,
    title: str,
    head: str,
    base: str,
    body: str,
) -> dict:
    owner, name = repo.split("/", 1)
    endpoint = f"https://{api_host}/api/v5/repos/{owner}/{name}/pulls"
    payload = {
        "access_token": token,
        "title": title,
        "head": head,
        "base": base,
        "body": body,
    }
    data = urlencode(payload).encode("utf-8")
    request = Request(
        endpoint,
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    try:
        with urlopen(request) as response:
            raw = response.read().decode("utf-8")
            return json.loads(raw)
    except HTTPError as err:
        raw = err.read().decode("utf-8", errors="replace")
        fail(f"Gitee API returned HTTP {err.code}: {raw}")
    except URLError as err:
        fail(f"Failed to reach Gitee API: {err.reason}")
    return {}


def validate_repo(repo: str) -> None:
    if repo.count("/") != 1:
        fail("Invalid --repo value. Use owner/repo format.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Auto commit, push branch, and create Gitee pull request.",
    )
    parser.add_argument("--remote", default="origin", help="Git remote name. Default: origin")
    parser.add_argument("--repo", help="Gitee repo in owner/repo format")
    parser.add_argument("--base", help="Target base branch")
    parser.add_argument("--head", help="Source branch (default: current branch)")
    parser.add_argument("--title", help="Pull request title")
    parser.add_argument("--body", help="Pull request body")
    parser.add_argument("--token", help="Gitee access token (default: $GITEE_TOKEN)")
    parser.add_argument("--api-host", default="gitee.com", help="Gitee host. Default: gitee.com")
    parser.add_argument(
        "--auto-commit",
        action="store_true",
        help="Commit uncommitted changes automatically before push",
    )
    parser.add_argument(
        "--commit-message",
        default="chore: prepare changes for gitee pr",
        help="Commit message used with --auto-commit",
    )
    parser.add_argument(
        "--no-push",
        action="store_true",
        help="Skip git push step",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print resolved values and skip API create",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_git_repo()

    head = args.head or current_branch()
    base = resolve_base_branch(args.remote, args.base)
    if head == base:
        fail("Head branch and base branch are the same. Choose a different --base or --head.")

    if working_tree_dirty():
        if args.auto_commit:
            auto_commit(args.commit_message)
        else:
            fail("Working tree has uncommitted changes. Use --auto-commit or commit manually.")

    repo = resolve_repo(args.remote, args.repo)
    validate_repo(repo)

    if not args.no_push:
        push_branch(args.remote, head)

    title = generate_title(args.title, args.remote, base, head)
    body = generate_body(args.body, args.remote, base, head)
    token = args.token or os.environ.get("GITEE_TOKEN", "")

    print(f"[INFO] repo={repo}")
    print(f"[INFO] remote={args.remote}")
    print(f"[INFO] head={head}")
    print(f"[INFO] base={base}")
    print(f"[INFO] title={title}")

    if args.dry_run:
        print("[INFO] dry-run enabled; skipping PR creation")
        print("----- PR Body Preview -----")
        print(body)
        return

    if not token:
        fail("Missing token. Set $GITEE_TOKEN or pass --token.")

    result = create_pull_request(args.api_host, repo, token, title, head, base, body)
    pr_url = result.get("html_url")
    pr_number = result.get("number")
    if pr_url:
        print(f"[OK] PR created: {pr_url}")
    else:
        print("[WARN] PR created but URL not found in response.")
        print(json.dumps(result, ensure_ascii=False, indent=2))
    if pr_number is not None:
        print(f"[OK] PR number: {pr_number}")


if __name__ == "__main__":
    main()
